# Setup
title:               Hiking by Transit
description:         'A collection of useful information for hiking by transit around Northern California.'
url:                 https://hikingbytransit.com
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Evan Tschuy
  url:               https://bsky.app/profile/tsch.uy

include: ['hikes', 'events', 'docs', 'public']
exclude: ['olmap', 'scripts']

# Gems
plugins:
  - jekyll-paginate

excerpt_separator: <!-- excerpt -->

# Custom vars
# version:             1.1.0
google_analytics_id: #UA-XXXX-Y
